declare const windowWidth: number;
declare const windowHeight: number;
declare const width: number;
declare const height: number;
declare function createCanvas(n1: number, n2: number): void;
declare function background(n: number): void;
declare function stroke(n: number): void;
declare function noFill(): void;
declare function point(x: number, y: number): void;
declare function random(r1: number): number;
declare function createInput(value: string, type: string): any;
declare function strokeWeight(n: number): void;
